apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: siz1zmkpm-go 
  janus-idp.io/tekton: siz1zmkpm-go
  backstage.io/kubernetes-id: siz1zmkpm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: siz1zmkpm-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml